### ISSUE TITLE
gif表情动画和白边

### ISSUE THREAD

**Issue by phperwuhan** [zsxsoft/danmu-client#11]
Dear zsx,

有个小问题哈：
我看到qq的gif表情在弹幕上显示起来是个静态的图片，没有动画效果，而且这些gif图片显示在黑色背景上是有白边的，知道怎么解决吗？

gif图片例子：
http://res.mail.qq.com/zh_CN/images/mo/DEFAULT2/32.gif

白边截图：
![qq 20150923173408](https://cloud.githubusercontent.com/assets/1720768/10041833/e159cd62-6219-11e5-9f10-7f2b551fcc20.png)

谢谢

**Comment by zsxsoft** [comment]
这个得去问QQ了，人没准压根没做透明也说不定
2015年9月23日 17:38于 phperwuhan notifications@github.com写道：Dear zsx,

有个小问题哈：
我看到qq的gif表情在弹幕上显示起来是个静态的图片，没有动画效果，而且这些gif图片显示在黑色背景上是有白边的，知道怎么解决吗？

gif图片例子：
http://res.mail.qq.com/zh_CN/images/mo/DEFAULT2/32.gif

白边截图：

谢谢
