### ISSUE TITLE
win8下不能用

### ISSUE THREAD

**Issue by phperwuhan** [zsxsoft/danmu-client#12]
Dear zsx,

我的同事发现在win8下客户端不能使用，是不是对win8不兼容啊？

谢谢

**Comment by zsxsoft** [comment]
没有这个可能，不能用倒是怎么不能用给个提示之类出来。我程序甚至在XP下都跑过。
On Oct 22, 2015 17:01, phperwuhan notifications@github.com wrote:Dear zsx,

我的同事发现在win8下客户端不能使用，是不是对win8不兼容啊？

谢谢

**Comment by phperwuhan** [comment]
sorry，知道原因了，已解决，谢谢。
