### ISSUE TITLE
按下回车/点击接受弹幕没反应

### ISSUE THREAD

**Issue by bviews** [zsxsoft/danmu-client#13]
调整好位置后，点击回车没反应还是一块黑屏。服务端配置在daocloud，改了客户端的config.js的地址，是不是要重新编译生成文件？

**Comment by zsxsoft** [comment]
我觉得只是你鼠标指针没点到黑窗体而已，用鼠标多点几次然后多按几次回车就好

**Comment by bviews** [comment]
我都已经移动窗体了再回车都不行，pd里面的win7，不是兼容性的问题吧？

2015年12月25日星期五，zsx notifications@github.com 写道：

**Comment by zsxsoft** [comment]
你把那个窗体截图发上来看下

**Comment by bviews** [comment]
![qq20151225-0](https://cloud.githubusercontent.com/assets/2810579/12003617/632150e6-ab61-11e5-90f5-cfc3f69bb8a2.png)

**Comment by zsxsoft** [comment]
检查以下问题：
1. 你的config.js是否修改正确？贴到http://www.bejson.com/看看。
2. 如果使用了记事本修改，请使用其它编辑器用【不带BOM头的UTF-8】保存。

我下个版本加一个验证config.js的功能好了。

**Comment by bviews** [comment]
```
({
    socket: {
        url: "http://bviews-danmu.daoapp.io",
        password: "123456",
        room: "default",
        heartbeat: 3000
    },
    display: {
        comment: {
            animationStyle: "scroll",
            fontStyle: "normal bold 5em 微软雅黑",
            fontColor: "rgb(255, 255, 255)",
            lifeTime: 240,
            height: 50
        },
        image: true
    },
    image: {
        regex: /\[IMG WIDTH=(\d+)\](.+?)\[\/IMG\]/ig,
        whitelist: [
            "https://www.baidu.com/img/bd_logo1.png",
            "http://www.baidu.com/img/bd_logo1.png",
        ]
    }
});
```

Config.js 如上，仅修改了url部分。
校验JSON的话因为key都不是string，而且包含在()里面是不通过的，
尝试用Sublime保存，Save with encoding --> UTF-8 以后还是失效

**Comment by zsxsoft** [comment]
尝试鼠标点击Panel后F12，输入
`
var windows = require('remote').getGlobal('windows');
windows.mainWindow.openDevTools({detach: true});
`
如果新打开的开发者工具中的错误信息是这样提示的，那应该就是config.js的问题。
![image](https://cloud.githubusercontent.com/assets/2398785/12003657/d2c2a4ac-ab63-11e5-8652-a0940f108483.png)
如果不是，还麻烦请再贴上来。

**Comment by bviews** [comment]
是这样的：
![qq20151226-0](https://cloud.githubusercontent.com/assets/2810579/12003673/8398d9ae-ab64-11e5-9bfd-f15b4ea31869.png)

**Comment by zsxsoft** [comment]
这看起来特么是打包成asar的问题啊我摔？！
你试试nwjs版本

**Comment by bviews** [comment]
nwjs版本如下：
![qq20151226-1](https://cloud.githubusercontent.com/assets/2810579/12003684/284cf890-ab65-11e5-9428-d6ada8414541.png)

**Comment by zsxsoft** [comment]
nwjs的话没有那个remote之类，你试试直接在那个console里require('./lib/danmu');看看效果

初步怀疑是路径问题（如图，我的路径是直接盘符开头）
![image](https://cloud.githubusercontent.com/assets/2398785/12003699/c4952d26-ab65-11e5-931b-a549cfa5363f.png)

如果可以的话，有什么能直接联系的方式吗？
我的联系方式可以打开我的GitHub主页 -> 网站首页 -> 鼠标下滑一屏获得。

**Comment by zsxsoft** [comment]
![image](https://cloud.githubusercontent.com/assets/2398785/12003705/f3298150-ab65-11e5-9e9b-c6ef845ec2e6.png)
 正常情况下在nwjs里应该这么显示
