### ISSUE TITLE
运行时调用electron-penetrate报错

### ISSUE THREAD

**Issue by commshare** [zsxsoft/danmu-client#14]
大神，您好，我执行electron .，报错：
J:\zsxsoft\danmu-client\node_modules\electron-penetrate\bindings-fork\inde…:87 Uncaught Error: A dynamic link library (DLL) initialization routine failed.
\?\J:\zsxsoft\danmu-client\node_modules\electron-penetrate\build\Release\penetrate.node

执行pack.ps1之后的exe后报错：
J:\zsxsoft\danmu-client\out\danmu-client-win32-x64\resources\app.asar\lib\…:43 弹幕初始化完成！
J:\zsxsoft\danmu-client\out\danmu-client-win32-x64\resources\app.asar\node…:92 Uncaught Error: Could not locate the bindings file. Tried:
 → J:\zsxsoft\danmu-client\build\penetrate.node
 → J:\zsxsoft\danmu-client\build\Debug\penetrate.node
 → J:\zsxsoft\danmu-client\build\Release\penetrate.node
 → J:\zsxsoft\danmu-client\out\Debug\penetrate.node
 → J:\zsxsoft\danmu-client\Debug\penetrate.node
 → J:\zsxsoft\danmu-client\out\Release\penetrate.node
 → J:\zsxsoft\danmu-client\Release\penetrate.node
 → J:\zsxsoft\danmu-client\build\default\penetrate.node
 → J:\zsxsoft\danmu-client\compiled\4.1.1\win32\x64\penetrate.node

可以麻烦您看下是怎么回事么？
谢谢！

**Comment by zsxsoft** [comment]
J盘是网络驱动器映射吧，你扔到本地硬盘就没问题了。原因没深究。
你是不是用的OS X+PD？如果是的话你可以直接用源码+Electron在OSX里跑的，只是缺少窗口穿透效果。

**Comment by zsxsoft** [comment]
看错了，无视第二句话，第一句话保持

**Comment by zsxsoft** [comment]
又看错了，无视上面那一层。。。

**Comment by commshare** [comment]
大神，J盘是移动硬盘，不是网络映射的，是win10 64位的系统，你release的1.04版本客户端，我部署到win10 x64 之后收不到弹幕，服务端在阿里云上。

服务端说1.04版本过老，是不是这个原因无法收到弹幕啊？
[2016-4-15 13:19:35.840] 检测到客户端/#TGcy1mUvS8KTcdczAAAA连接
[2016-4-15 13:19:37.533] 该版本弹幕客户端过老，请更新弹幕客户端。

客户端编译git上的最新版都通过了：
PS J:\media\XLIVE\danmaku\node\zsxsoft\danmu-client> .\pack.ps1
 uilding electron-penetrate
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@5.6.0 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\node-gyp\gyp\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'J:\media\XLIVE\danmaku\node\zsxsoft\danmu-client\node_modules\electron-penetrate\build\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\Users\Administrator\AppData\Roaming\npm\node_modules\node-gyp\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\Users\Administrator\.node-gyp\0.35.1\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\Users\Administrator\.node-gyp\0.35.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\Users\Administrator\AppData\Roaming\npm\node_modules\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=J:\media\XLIVE\danmaku\node\zsxsoft\danmu-client\node_modules\electron-penetrate',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'J:\media\XLIVE\danmaku\node\zsxsoft\danmu-client\node_modules\electron-penetrate\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=Win32' ]
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  penetrate.cc
  win_delay_load_hook.c
     正在创建库 J:\media\XLIVE\danmaku\node\zsxsoft\danmu-client\node_modules\electron-penetrate\build\Release\penetrate.lib 和对象 J:\media\XLIV
E\danma
  ku\node\zsxsoft\danmu-client\node_modules\electron-penetrate\build\Release\penetrate.exp
  正在生成代码
  已完成代码的生成
  penetrate.vcxproj -> J:\media\XLIVE\danmaku\node\zsxsoft\danmu-client\node_modules\electron-penetrate\build\Release\penetrate.node
gyp info ok
electron-penetrate successful built!
Building windows-caption-color
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@5.6.0 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\node-gyp\gyp\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'J:\media\XLIVE\danmaku\node\zsxsoft\danmu-client\node_modules\windows-caption-color\build\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\Users\Administrator\AppData\Roaming\npm\node_modules\node-gyp\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\Users\Administrator\.node-gyp\0.35.1\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\Users\Administrator\.node-gyp\0.35.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\Users\Administrator\AppData\Roaming\npm\node_modules\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=J:\media\XLIVE\danmaku\node\zsxsoft\danmu-client\node_modules\windows-caption-color',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'J:\media\XLIVE\danmaku\node\zsxsoft\danmu-client\node_modules\windows-caption-color\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=Win32' ]
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  color.cc
..\color.cc(10): warning C4996: 'GetVersion': 被声明为已否决 [J:\media\XLIVE\danmaku\node\zsxsoft\danmu-client\node_modules\windows-caption-color
\build
\color.vcxproj]
          C:\Program Files (x86)\Windows Kits\8.1\Include\um\sysinfoapi.h(110) : 参见“GetVersion”的声明
..\color.cc(20): warning C4172: 返回局部变量或临时变量的地址 [J:\media\XLIVE\danmaku\node\zsxsoft\danmu-client\node_modules\windows-caption-color
\build\color.
vcxproj]
  win_delay_load_hook.c
     正在创建库 J:\media\XLIVE\danmaku\node\zsxsoft\danmu-client\node_modules\windows-caption-color\build\Release\color.lib 和对象 J:\media\XLIVE
\danmak
  u\node\zsxsoft\danmu-client\node_modules\windows-caption-color\build\Release\color.exp
  正在生成代码
  已完成代码的生成
  color.vcxproj -> J:\media\XLIVE\danmaku\node\zsxsoft\danmu-client\node_modules\windows-caption-color\build\Release\color.node
gyp info ok
windows-caption-color successful built!
Packaging app for platform win32 ia32 using electron v0.35.1
Wrote new app to out\danmu-client-win32-ia32
Building electron-penetrate
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@5.6.0 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\node-gyp\gyp\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'J:\media\XLIVE\danmaku\node\zsxsoft\danmu-client\node_modules\electron-penetrate\build\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\Users\Administrator\AppData\Roaming\npm\node_modules\node-gyp\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\Users\Administrator\.node-gyp\0.35.1\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\Users\Administrator\.node-gyp\0.35.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\Users\Administrator\AppData\Roaming\npm\node_modules\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=J:\media\XLIVE\danmaku\node\zsxsoft\danmu-client\node_modules\electron-penetrate',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'J:\media\XLIVE\danmaku\node\zsxsoft\danmu-client\node_modules\electron-penetrate\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  penetrate.cc
  win_delay_load_hook.c
     正在创建库 J:\media\XLIVE\danmaku\node\zsxsoft\danmu-client\node_modules\electron-penetrate\build\Release\penetrate.lib 和对象 J:\media\XLIV
E\danma
  ku\node\zsxsoft\danmu-client\node_modules\electron-penetrate\build\Release\penetrate.exp
  正在生成代码
  已完成代码的生成
  penetrate.vcxproj -> J:\media\XLIVE\danmaku\node\zsxsoft\danmu-client\node_modules\electron-penetrate\build\Release\penetrate.node
gyp info ok
electron-penetrate successful built!
Building windows-caption-color
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@5.6.0 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\node-gyp\gyp\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'J:\media\XLIVE\danmaku\node\zsxsoft\danmu-client\node_modules\windows-caption-color\build\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\Users\Administrator\AppData\Roaming\npm\node_modules\node-gyp\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\Users\Administrator\.node-gyp\0.35.1\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\Users\Administrator\.node-gyp\0.35.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\Users\Administrator\AppData\Roaming\npm\node_modules\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=J:\media\XLIVE\danmaku\node\zsxsoft\danmu-client\node_modules\windows-caption-color',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'J:\media\XLIVE\danmaku\node\zsxsoft\danmu-client\node_modules\windows-caption-color\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  color.cc
..\color.cc(10): warning C4996: 'GetVersion': 被声明为已否决 [J:\media\XLIVE\danmaku\node\zsxsoft\danmu-client\node_modules\windows-caption-color
\build
\color.vcxproj]
          C:\Program Files (x86)\Windows Kits\8.1\Include\um\sysinfoapi.h(110) : 参见“GetVersion”的声明
..\color.cc(20): warning C4172: 返回局部变量或临时变量的地址 [J:\media\XLIVE\danmaku\node\zsxsoft\danmu-client\node_modules\windows-caption-color
\build\color.
vcxproj]
  win_delay_load_hook.c
     正在创建库 J:\media\XLIVE\danmaku\node\zsxsoft\danmu-client\node_modules\windows-caption-color\build\Release\color.lib 和对象 J:\media\XLIVE
\danmak
  u\node\zsxsoft\danmu-client\node_modules\windows-caption-color\build\Release\color.exp
  正在生成代码
  已完成代码的生成
  color.vcxproj -> J:\media\XLIVE\danmaku\node\zsxsoft\danmu-client\node_modules\windows-caption-color\build\Release\color.node
gyp info ok
windows-caption-color successful built!
Packaging app for platform win32 x64 using electron v0.35.1
Wrote new app to out\danmu-client-win32-x64
PS J:\media\XLIVE\danmaku\node\zsxsoft\danmu-client>

**Comment by zsxsoft** [comment]
服务端的话匹配1.04也要用Release里的，直接clone master分支拿的匹配的就是client的master分支。

仔细读了一下你的错误信息，感觉不太科学，我明天重新release下看看确认下。你也试试x86版本的out？

**Comment by commshare** [comment]
谢谢大神！

我使用ia32版本，可以收到弹幕！

虽然依旧有报错，但是不影响：

弹幕初始化完成！
J:\media\XLIVE\danmaku\node\zsxsoft\danmu-client\out\danmu-client-win32-ia32\resources\app.asar\nod…:92 Uncaught Error: Could not locate the bindings file. Tried:
 → J:\media\XLIVE\danmaku\node\zsxsoft\danmu-client\build\penetrate.node
 → J:\media\XLIVE\danmaku\node\zsxsoft\danmu-client\build\Debug\penetrate.node
 → J:\media\XLIVE\danmaku\node\zsxsoft\danmu-client\build\Release\penetrate.node
 → J:\media\XLIVE\danmaku\node\zsxsoft\danmu-client\out\Debug\penetrate.node
 → J:\media\XLIVE\danmaku\node\zsxsoft\danmu-client\Debug\penetrate.node
 → J:\media\XLIVE\danmaku\node\zsxsoft\danmu-client\out\Release\penetrate.node
 → J:\media\XLIVE\danmaku\node\zsxsoft\danmu-client\Release\penetrate.node
 → J:\media\XLIVE\danmaku\node\zsxsoft\danmu-client\build\default\penetrate.node
 → J:\media\XLIVE\danmaku\node\zsxsoft\danmu-client\compiled\4.1.1\win32\ia32\penetrate.nodebindings @ J:\media\XLIVE\danmaku\node\zsxsoft\danmu-client\out\danmu-client-win32-ia32\resources\app.asar\nod…:92module.exports.penetrate @ J:\media\XLIVE\danmaku\node\zsxsoft\danmu-client\out\danmu-client-win32-ia32\resources\app.asar\nod…:4module.exports.init @ J:\media\XLIVE\danmaku\node\zsxsoft\danmu-client\out\danmu-client-win32-ia32\resources\app.asar\lib…:5initFunction @ index.js:40keydownFunction @ index.js:48
J:\media\XLIVE\danmaku\node\zsxsoft\danmu-client\out\danmu-client-win32-ia32\resources\app.asar\lib…:30 已连接上弹幕服务器
2J:\media\XLIVE\danmaku\node\zsxsoft\danmu-client\out\danmu-client-win32-ia32\resources\app.asar\lib…:33 得到1条弹幕

**Comment by zsxsoft** [comment]
弹幕倒是不影响，那个就是让窗口可穿透的

**Comment by commshare** [comment]
是的，penetrate是用来穿透的。我再多试试哈！

**Comment by zsxsoft** [comment]
`npm install`有什么错误提示
