### ISSUE TITLE
多系统打包支持

### ISSUE THREAD

**Issue by zsxsoft** [zsxsoft/danmu-client#16]
检查了一下，Electron不知道从哪个版本开始有了``setIgnoreMouseEvents``，所以``electron-penetrate``已经失去了存在的意义，而且这个还能支持macOS了。

所以接下来的进度：
- [x] Deprecate electron-penetrate.
- [x] Try to find other Electron package tool to replace the PowerShell.
- [x] Release 1.0.8, release macOS version.

BTW, ``window-caption-color`` should be removed too, but is there any other UI design?

**Comment by zsxsoft** [comment]
npm deprecate electron-penetrate "Use win.setIgnoreMouseEvents instead: https://electron.atom.io/docs/api/browser-window/#winsetignoremouseeventsignore" --registry=https://registry.npmjs.org/

**Comment by Magic-Bytes** [comment]
感觉这个项目很有意思，什么时候能够打包发布macOS版？

**Comment by zsxsoft** [comment]
@jackandjohn 当我有心情的时候……macOS / Linux用户其实我觉得根本不需要打包的，直接几行代码敲下去就能跑了
```
npm install electron -g
git clone https://github.com/zsxsoft/danmu-client/
npm install 
electron .
```

不过你倒是提醒了我一点，里面的依赖挺久没更新了，回头更新一下

**Comment by jackandjohn** [comment]
那么macOS版本中，如何支持点击穿透呢？

**Comment by jackandjohn** [comment]
macOS版本需要如何修改代码，支持点击穿透？

**Comment by zsxsoft** [comment]
已经可以通过CI打包，回头release
