### ISSUE TITLE
求弹幕界面支持微信的表情图片

### ISSUE THREAD

**Issue by lovaxi** [zsxsoft/danmu-client#3]
目前都是以字符的方式展示的

PS：你的作品很棒

谢谢

**Comment by zsxsoft** [comment]
你说的是☺ ☹ ☻ 这些Emoji字符表现为图片形式吗……可能有点麻烦……
大概要实现一套支持图片的弹幕了，等有时间搞吧……抱歉……

**Comment by lovaxi** [comment]
对的，因为很多内容都是从微信发出的。图片会变成字符

从逻辑上要实现的话，确实需要本地有一套这个表情库

或者你看看有没有我可以支持的地方

非常感谢

**Comment by zsxsoft** [comment]
凑，我看了下，从微信复制出来的不是Emoji字符……
我用表情功能发了个笑脸，出来的东西居然是`/::)`……我还以为会变成这个→ ☺

如果你要把`/::)`变成微信的图片的话，比较难做。如果只有图片，没有文字的话反而好做。
**因为涉及到了图文混排，你要找到原来/::)字符的位置然后把这块覆盖掉。**
这部分的修改在客户端里，要修改lib/danmu/danmu/comment.js里的draw方法。找到text内的`/::)`在画布内的所在位置，然后把这个用你的图片覆盖掉。

如果你要把`/::)`变成☺的话，那就简单了。
你可以选择参照[danmu-server里面的ext/ext/weibo/index.js](https://github.com/zsxsoft/danmu-server/blob/master/lib/ext/ext/weibo/index.js#L133)，在danmuTransfer事件挂一个监听器，然后替换文字。如

``` javascript
item.text = item.text.replace(/\/\:\:\)/g, "☺");
```

也可以选择在client里绘画的时候把文字替换掉，位置同上面图片，只要简单地在下面这行往画布上绘画文字之前替换文字就好。

``` javascript
canvasContext.fillText(this.text, this.x, this.y + this.height); 
```

你打算怎么处理？

**Comment by zsxsoft** [comment]
如果图文混排的话，你可以尝试这样（伪代码）：

``` javascript
var regex = /某一定能匹配到表情符号的正则/g;
var ret = null;
var lastIndex = 0;  // 记录未写入文字的起始点
while ((ret = regex.exec(this.text)) != false) {
    canvasContext.fillText(this.text.splice(lastIndex, ret.lastIndex), ...otherArguments); // 绘制表情图片前的文字
    canvasContext.drawImage(imageElement, ..otherArguments); // 绘制表情图片
    lastIndex = ret.lastIndex + ret[0].length; // 更新未写入文字的起始点
}
```

我得研究一下怎么搞，因为这些图片大小不知道，和不同字体摆在一起要怎么排也得研究……

另外我发现client里要扩展似乎有点麻烦，需要弹幕Object的style设置为Custom，而且似乎还有点BUG，得看看怎么搞。

（如果你有什么好的解决方案，欢迎Pull Request。）

**Comment by zsxsoft** [comment]
更新了一个图文混排的简单解决方案（虽然全部注释了），可以看看

**Comment by phperwuhan** [comment]
Dear zsxsoft,

微信中的表情实际有3种：qq表情、emoji、其他扩展表情
qq表情是微信默认就有的表情，使用最多；
emoji表情主要是ios客户端在使用，也就是ios默认输入法中的表情；
其他扩展表情主要是需要用户安装才能用。

其实如果能把qq表情和emoji表情实现就已经足够了。

但是qq表情和emoji表情他们从微信服务器传过来的编码又是不同的，而且网页上也不能直接显示，所以我想了一个更简单的更通用的方案看能否支持这种需求：
归根结底表情的显示其实就是图片的显示，而且在不同屏幕上显示的比例又可能不同，所以我建议你的客户端能否做一点修改，就是根据内容中的图片标签中的src、width、height属性直接显示图片就行了，其中的图片内容你不用管是表情还是别的什么，这样做通用性会更好，例如直接显示图片：
![temp](https://cloud.githubusercontent.com/assets/1720768/9577361/b222968c-5012-11e5-8cea-50ee030cd567.png)
其中的属性只有src/width/height，图片尺寸最好能根据字体大小缩放比例。

那么需求就变成了：简单的显示混和图文到客户端就行了，显示什么图片完全由发送方解析和转换成相应的图片img标签就行了。

你看这样做是否可行？

谢谢。

**Comment by zsxsoft** [comment]
@phperwuhan
我已经把简单的混合图文实现了，如图：
![qq 20150831191148](https://cloud.githubusercontent.com/assets/2398785/9577524/25232024-5014-11e5-8848-ba9e8099f3c1.jpg)
Commit见：https://github.com/zsxsoft/danmu-client/commit/39a9bd02828742e065396a1c52945fee5b91e340

出于某些原因，我暂时将其注释。你可以将其打开试试。
目前还没有做动态获取图片大小功能，想想麻烦就不做了，以后固定大小即可。接着就是动态的间距设定，得根据字号判断，可能比较麻烦。
为确保效率，我这里是用Canvas画布实现的，所以这些东西必须自己计算自己画，如果有DOM那样简单的管理工具还好些，不过那样效率实在太低了。

**Comment by phperwuhan** [comment]
Dear zsxsoft,

就是你2天前改的代码，对吧？明天我试一下。

我看到你的截图里面图片和文字有时会重叠，用canvas画布实现客户端的展现是不是不好控制样式和图文混排啊？如果改成类似于普通网页的方式，弄个透明层+css/div+js控制内容滚动，这样样式控制起来是不是就容易很多了？改成这种方式是不是难度很大？能不能提供一点修改的线索和思路，我找精通前端（css/div+js）的人看看能否按这个思路改改来实现客户端的展现。

**Comment by zsxsoft** [comment]
@phperwuhan 
那个重叠只是两条弹幕重叠了而已，并不是不好控制的问题。
用画布实现的话，自由度太大，什么都没有，导致一切都要自己去算，所以会比较麻烦。
你可以直接`lib/danmu/danmu`里面的内容整个换掉，然后在`lib/danmu/index.js`调整下接口就可以了。不过，用canvas的原因是因为两点：DOM效率低、可以用GPU加速。用DOM来控制的话的确会方便很多（js只要控制那个div的`height`和`width`就可以了），但可能支撑不了太多条。如果真的要用DOM的话，我认为还是用CSS3动画来控制弹幕的显示比较合适，js只需要负责运算初始值和回收DOM，还可以有效利用GPU。我简单用“danmaku”关键词在GitHub搜了一下，第一页基本上都是`canvas`的。

**另外，我那天写的代码还可以进一步优化。以下是可能的优化方案：**
1. 在第一次绘画时直接缓存这块区域的内容，下次直接取出；
2. 制作缓存超时机制，保证内存占用；
3. 直接在正则内直接文字进行替换，计算出大概需要的空格数后直接画，然后再一次性画图。

**Comment by zsxsoft** [comment]
搜到一个库，jQuery的，可以研究，https://github.com/chiruom/jquery.danmu.js

**Comment by zsxsoft** [comment]
图片弹幕已完整支持，关闭Issue。
