### ISSUE TITLE
咨询下textStyle中如何设置字体大小

### ISSUE THREAD

**Issue by lovaxi** [zsxsoft/danmu-client#4]
我用size：xxpx或者直接设置xxPX

字体大小都没变化

而且我发现设置textStyle貌似没啥影响

**Comment by zsxsoft** [comment]
在根目录的config.js里有统一配置

**Comment by lovaxi** [comment]
我不是这个意思，我知道根目录下有统一配置

我希望每次发出去的文字都可以调整尺寸，这个可能么？textStyle不能调整尺寸？

**Comment by zsxsoft** [comment]
你可以参考下danmu-server的/advanced发送接口，打开http://127.0.0.1:3000/advanced即可

**Comment by zsxsoft** [comment]
https://github.com/zsxsoft/danmu-server/blob/master/lib/http/route/post.js

``` javascript
danmuData.style = req.body.style;
danmuData.textStyle = req.body.textStyle;
danmuData.lifeTime = req.body.lifeTime;
danmuData.color = req.body.color;
```

格式的话，参考config.js的配置

**Comment by zsxsoft** [comment]
论文档没写清楚的害处，明天我把这两个东西的文档全部补全。

**Comment by lovaxi** [comment]
哈哈，谢谢。

normal bold 3em 微软雅黑

只改这个数字，不改动其他的，就可以调整大小了

谢谢
