### ISSUE TITLE
怎么控制弹幕滚动的速度和控制弹出速度尽量均匀

### ISSUE THREAD

**Issue by phperwuhan** [zsxsoft/danmu-client#5]
Dear zsx,

2个问题请教一下，可能一个是客户端的一个服务端的：

1、怎么控制客户端中弹幕滚动的速度呢？照默认速度从右向左滚动速度有点快；

2、怎么控制弹幕内容弹出速度尽量均匀，不要一次出现太多内容，一下又没有内容：特别在高并发情况下可能出现一下弹出很多弹幕的情况，等高并发过去以后就一下没有内容，不知道能否控制弹幕内容不管是否处于高并发期都能比较均匀的按一定频率弹出内容？

谢谢。

**Comment by zsxsoft** [comment]
1. config.js里`lifeTime`调大一点即可
2. danmu-server里config的`websocket.singlesize`

**Comment by zsxsoft** [comment]
服务器方面的队列功能就是为防止第二种情况的。把弹幕队列池设置大一点，再把发送间隔定低一点、发送条数定低一点，就OK

**Comment by phperwuhan** [comment]
Great!
