### ISSUE TITLE
当第一行字符设置得比较大时会出现文字顶部被截断的情况

### ISSUE THREAD

**Issue by phperwuhan** [zsxsoft/danmu-client#6]
如下图：
![temp](https://cloud.githubusercontent.com/assets/1720768/9597798/e62dd28e-50b7-11e5-9ba5-e1f4056bb2bf.png)

**Comment by zsxsoft** [comment]
我这里的失误。如果要动态大小的话height也要随之发送才可以，服务器端还没有发送height的办法。得看看怎么弄。

**Comment by zsxsoft** [comment]
服务器那更新了，客户端也得更新。

**Comment by zsxsoft** [comment]
客户端更新了

**Comment by phperwuhan** [comment]
这个问题貌似还是有：
![qq 20150907154901](https://cloud.githubusercontent.com/assets/1720768/9711744/8b9edc6c-5578-11e5-9e3d-be6a655c241e.png)

**Comment by zsxsoft** [comment]
这个问题你要检查下高度设置的对不对，一般1em就需要100的高度。
