### ISSUE TITLE
弹幕池小问题

### ISSUE THREAD

**Issue by phperwuhan** [zsxsoft/danmu-client#7]
这个弹幕池（就是启动客户端时的那个黑色屏幕）在IE10下把屏幕拉大按enter就没反应了，在8和11的版本下是ok的。
![temp1](https://cloud.githubusercontent.com/assets/1720768/9600662/dc0dad08-50ce-11e5-9f58-a173cf413b29.png)

**Comment by zsxsoft** [comment]
不是太懂意思，你是说这后面是IE10的时候Enter没反应？
这事一般你多按几次Enter就成，如果无效就检查下你的焦点是不是在这个窗口上，先用鼠标点一下窗口再Enter.

**Comment by phperwuhan** [comment]
对的，是IE10的时候Enter没反应？我的同事测试了好多次。
IE8和IE11下是好的。

**Comment by zsxsoft** [comment]
并不是，我认为只是你焦点没点到窗口而已。实在不行重新开一遍程序就好。

**Comment by zsxsoft** [comment]
另外，喜欢请点个Star :)

**Comment by phperwuhan** [comment]
star已点，哈哈

我的同事测试了多次一直不行哦 
在IE10下把屏幕拉大总是不行哦

**Comment by zsxsoft** [comment]
事实上我还是认为是哪里操作没做对的，因为这里的逻辑是监听这个窗口的keydown事件。不过反正如果真有问题的话切到其他窗口后回车再切到IE10下也不是什么事么

**Comment by phperwuhan** [comment]
嗯，明天我们同事再多找几个ie10的系统看一下，怀疑是不是安装了什么插件导致的。

**Comment by phperwuhan** [comment]
确认是由于拖动屏幕大小时不小心点了其他地方引起的。

貌似拖动屏幕大小时需要十分小心，只能拖动红色边框来操作，如果期间点了别的地方再回车可能会不能用。

有没有什么可以优化一下的办法来杜绝这种问题的发生呢？

谢谢。

**Comment by zsxsoft** [comment]
直接在任务栏里切换到那个窗口就可以了
