### ISSUE TITLE
包含图片时弹幕滚动速度不受控制

### ISSUE THREAD

**Issue by phperwuhan** [zsxsoft/danmu-client#8]
Dear zsx,

发现个小问题：当弹幕中包含图片表情时滚动速度变得较快，不受lifeTime参数控制，其他不包含图片的弹幕滚动速度正常。貌似表情图片越多滚动越快，表情图片我都是放在末尾，引用的是外网图片。

我的测试环境参数：
服务端："interval": 5000
客户端：
lifeTime: 2000
height: 70

谢谢

**Comment by zsxsoft** [comment]
可能是因为我这里lifeTime实际上是以配置为基础，根据弹幕总字数再加以运算的结果。如果我没记错的话，在server的transfer部分。现在在学校，不太清楚。
2015年9月4日 18:56于 phperwuhan notifications@github.com写道：Dear zsx,

发现个小问题：当弹幕中包含图片表情时滚动速度变得较快，不受lifeTime参数控制，其他不包含图片的弹幕滚动速度正常。貌似表情图片越多滚动越快，这边表情图片我都是放在末尾。

我的测试环境参数：
服务端："interval": 5000
客户端：lifeTime: 2000

谢谢

**Comment by phperwuhan** [comment]
是不是因为是根据服务端发送的内容做的长度判断及速度控制，而没有根据最终显示的内容长度控制的速度？因为图片所占用的内容长度比一般的文字要多很多。

**Comment by zsxsoft** [comment]
嗯，初步怀疑是这个原因
2015年9月6日 21:53于 phperwuhan notifications@github.com写道：是不是因为是根据服务端发送的内容做的长度判断及速度控制，而没有根据最终显示的内容长度控制的速度？因为图片所占用的内容长度比一般的文字要多很多。

**Comment by phperwuhan** [comment]
啥时候有空处理一下？期待中:)

**Comment by phperwuhan** [comment]
创建了pull  request，麻烦抽空check一下修改的是否可靠。

之所以一个图片要占用4个Q字符是因为，我这里设置的图片高宽都是70，如果设置为3个或更少，会发生表情图片在滚动并最后离开屏幕边缘时会提前消失，设置为4个Q字符则刚刚好一般不会出现此问题。
不知有没有更好的解决办法，请赐教:)

**Comment by zsxsoft** [comment]
选择在服务端操作，见https://github.com/zsxsoft/danmu-server/commit/c3397c82088d1e1ddbd899042d0b38783d2db075
