### ISSUE TITLE
缓存的本地图片第一次不能显示

### ISSUE THREAD

**Issue by phperwuhan** [zsxsoft/danmu-client#9]
Dear zsx,

又发现一个小问题：
当我发送本地图片的代码时，每个本地图片第一次都不能显示出来，只有第二次以后才能显示，估计是因为第一次显示的时候缓存里面没有图片导致的？这里的缓存是不是指客户端的缓存？是缓存到哪里了？

**Comment by zsxsoft** [comment]
是的，我没有设预读取。
2015年9月7日 10:27于 phperwuhan notifications@github.com写道：Dear zsx,

又发现一个小问题：
当我发送本地图片的代码时，每个本地图片第一次都不能显示出来，只有第二次以后才能显示，估计是因为第一次显示的时候缓存里面没有图片导致的？这里的缓存是不是指客户端的缓存？是缓存到哪里了？

**Comment by phperwuhan** [comment]
啥时候有空处理一下？期待中:)

建议在显示的时候判断一下是否有缓存，如果缓存了就直接从缓存显示，否则先缓存再从缓存显示。

**Comment by zsxsoft** [comment]
一直都有缓存。
我在学校
2015年9月7日 14:26于 phperwuhan notifications@github.com写道：啥时候有空处理一下？期待中:)

建议在显示的时候判断一下是否有缓存，如果缓存了就直接从缓存显示，否则先缓存再从缓存显示。

**Comment by phperwuhan** [comment]
亲，

这个缓存的本地图片第一次不能显示问题貌似还是存在哦。第一次不能显示，但是第二次以后都可以显示。

另外，这个问题也是貌似还有：
https://github.com/zsxsoft/danmu-client/issues/6

**Comment by zsxsoft** [comment]
这个其实我其实是暂时没打算处理来着，想让浏览器顺其自然自动加载自动缓存。。

**Comment by phperwuhan** [comment]
有啥办法可以临时解决一下的？我不知道改哪里，也不知道怎么改。。。

**Comment by zsxsoft** [comment]
具体思路是直接把我生成的那个image对象直接append到document.body里，onload后再drawImage，或者直接在程序启动时直接加载所有白名单内图片。反正无论怎么搞效果我估计都不会太好，没测试过。

搜索下[canvas 图片 预加载]或[canvas image preload]

**Comment by phperwuhan** [comment]
如果我在comment.js的第23行，即：
var imageCache = {}; // 图像DOM缓存
这一行下面循环加入对本地或外网的图片缓存到这个imageCache变量是不是就可以实现预缓存了？但是，我看到这个imageCache变量貌似是一个局部变量并且初始值是一个空的对象，如果我这样做是不是会导致每次显示每个弹幕时都会重复循环缓存所有图片到这个imageCache变量中去呢？是不是会严重影响性能？

**Comment by phperwuhan** [comment]
我上面说的对吗？
如果要一次缓存所有图片，不知怎么改在哪里改？。。。

**Comment by zsxsoft** [comment]
我得回去试验下，目前不确定

**Comment by zsxsoft** [comment]
你把图片放在本地吧，本地的不会出现这种问题。互联网的首次必须要下载，不然连宽度等都无法确定。

**Comment by zsxsoft** [comment]
调整了一下，针对网络图片加了预读，但本地的可以直接被显示的，所以就不加了。

**Comment by phperwuhan** [comment]
好的，我会再测试一下的，谢谢。

PS：我之前测试这个问题都是在客户端本地图片进行的测试哦，不是网络图片。我是在客户端目录下开了几个emotions/qq/...和emotions/emoji/...这样的子目录来保存的图片，然后在发弹幕时通过相对路径来引用这些图片的，一直都有这个问题哦。。。
也就是相同的表情图片的弹幕中第一次被引用时是不能显示出来的，当第二次被引用时就可以显示，第三次第四次。。。都可以显示，也就是说只有第一次是不行的。
重现这个问题有个要求：首先需要关闭客户端，然后再启动客户端开始接收弹幕才会发现这个问题，否则可能无法重现。

**Comment by zsxsoft** [comment]
OK，我再测试下。

**Comment by zsxsoft** [comment]
这样吧，因为我又回了学校（高三真麻烦），你把那些本地图片加入白名单测试一下？如果不行，就用绝对路径，以file协议加入那个白名单再测试一下？

如果我要做本地图片缓存的话，因为没有那个白名单的List，这样就得扫描自己目录下全部的图片文件了，直接感觉很SB。

如果你想自己实现一下的话，参照一下我的那个commit？

**Comment by phperwuhan** [comment]
Dear zsx,

我用最新代码测试了一下，貌似这次大改以后即使不设置preload参数并且把whitelist留空也能在第一次时显示图片哦，也就是解决了第一次图片不能显示的问题。所以我猜测是不是之前的代码哪里有问题导致的，在这次的修改中被解决掉了。

为了保持一致性，我把我本地的preload参数还是设置为了true。

这个问题测试下来是ok的！

谢谢

**Comment by zsxsoft** [comment]
大改？什么鬼，是说抽离吗。。

**Comment by phperwuhan** [comment]
对啊 就是针对这个bug的修改哦
